Pages/Cart/Cart.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
//using Microsoft.AspNetCore.Mvc.IActionResult;
using Microsoft.EntityFrameworkCore;
using WebShopRM.Helpers;
using WebShopRM.Models;
using Microsoft.AspNetCore.Http;
using WebShopRM.Pages;
using WebShopRM.Pages.Products;

namespace WebShopRM.Pages.Cart
{
    public class CartModel : PageModel
    {
        private readonly WebShopRM.Models.WebShopRMContext _context;
        //private readonly object ViewBag;

        public CartModel(WebShopRM.Models.WebShopRMContext context)
        {
            _context = context;
        }
        //public CartItem cartItem { get; set; }

        public List<CartItem> cart { get; set; }
        public double Total { get; set; }

        public Product product { get; set; }

        [BindProperty]
        public int Id { get; set; }
        public void OnGet()
        {
            cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");
            decimal a = cart.Sum(i => i.Product.Price * i.Quantity).Value;
            Total = Decimal.ToDouble(a);
        }
        
        public IActionResult OnGetBuy(int id)
        {
            cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");
            if (cart == null)
            {
                cart = new List<CartItem>();
                cart.Add(new CartItem
                {
                    Product = _context.Product.Find(id),
                    Quantity = 1
                });
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            else
            {
                int index = Exists(cart, id);
                if (index == -1)
                {
                    cart.Add(new CartItem
                    {
                        Product = _context.Product.Find(id),
                        Quantity = 1
                    });
                }
                else
                {
                    cart[index].Quantity++;
                }
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            return RedirectToPage("Cart");
        }

        public IActionResult OnGetRemove(int id)
        {
            cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");
            int index = Exists(cart, id);
            cart.RemoveAt(index);
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            return RedirectToPage("Cart");
        }

        public IActionResult OnPostUpdate(int [] quantities)
        {
            cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");
            for (var i =0;i<cart.Count;i++)
            {
                cart[i].Quantity = quantities[i];
            }
            return RedirectToPage("Cart");
        }

        private int Exists(List<CartItem> cart, int id)
        {
            for (var i = 0; i < cart.Count; i++)
            {
                if (cart[i].Product.Id == id)
                {
                    return i;
                }
            }
            return -1;
        }



        //public IActionResult OnGet()//rename
        //{
        //    //todo move this method to own place
        //    var cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");
        //    ViewData["cart"] = cart;
        //    ViewData["total"] = cart.Sum(item => item.Product.Price * item.Quantity);

        //    return Page();
        //}

        //[Route("buy/{id}")]
        //public ActionResult Buy(int id)
        //public IActionResult OnPostBuy(int id)
        //{
        //    if (SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart") == null)
        //    {
        //        List<CartItem> cart = new List<CartItem>();
        //        cart.Add(new CartItem { Product = _context.Product.Find(id), Quantity = 1 });
        //        SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
        //    }
        //    else
        //    {
        //        List<CartItem> cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");
        //        int index = isExist(id);
        //        if (index != -1)
        //        {
        //            cart[index].Quantity++;
        //        }
        //        else
        //        {
        //            cart.Add(new CartItem { Product = _context.Product.Find(id), Quantity = 1 });
        //        }
        //        SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
        //    }
        //    return RedirectToAction("index");
        //}


        public IActionResult Remove(int id)
        {
            List<CartItem> cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");
            int index = isExist(id);
            cart.RemoveAt(index);
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            return RedirectToAction("Index");
        }

        private int isExist(int id)
        {
            List<CartItem> cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");
            for (int i = 0; i < cart.Count; i++)
            {
                if (cart[i].Product.Id.Equals(id))
                {
                    return i;
                }
            }
            return -1;
        }
    }
}
    //    //ChienVH https://www.youtube.com/watch?v=h_jfcLICk_8
    //    //ShoppingCart "controller"
    //    private string strCart = "Cart";
    //    //Get: ShoppingCart 
    //    public ActionResult Index()
    //    {
    //        return Index();//View();
    //    }
    //    public ActionResult OrderNow(int? id)
    //    {
    //        if (id == null)
    //        {
    //            //return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
    //            return BadRequest();
    //        }
    //        if (HttpContext.Session.GetString(strCart) == null)
    //        {
    //            List<CartItem> lsCart = new List<CartItem>();

    //            //new CartItem ( _context.Product.Find(id, 1)) //fixa konstruktorn?
    //            lsCart.Add(new CartItem { Product = _context.Product.Find(id), Quantity = 1 });
    //            SessionHelper.SetObjectAsJson(HttpContext.Session, "stCart", lsCart);
    //            //List<CartItem> cart = new List<CartItem>();
    //            //    cart.Add(new CartItem { Product = _context.Product.Find(id), Quantity = 1 });
    //            //    SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);



    //        }
    //        else
    //        {
    //            List<CartItem> lsCart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "strCart");
    //            int check = isExist(id);
    //            if (check != -1)
    //                lsCart[check].Quantity++;
    //            else
    //                lsCart.Add(new CartItem { Product = _context.Product.Find(id), Quantity = 1 });

    //            SessionHelper.SetObjectAsJson(HttpContext.Session, "strCart", lsCart);
    //        }
    //        return Index(); //View();
    //    }
    //}
    //private int IsExist(string id)//looking for double items
    //{
    //    //List<CartItem> lsCart = (List<CartItem>)Session[strCart];
    //    List<CartItem> lsCart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "lsCart");
    //    for (int i = 0; i < lsCart.Count; i++)
    //    {
    //        if (lsCart[i].Product.Id.Equals(id))
    //        {
    //            return i;
    //        }
    //    }
    //    return -1;
    //}
//}
    

Pages/Categories/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebShopRM.Models;

namespace WebShopRM.Pages.Categories
{
    public class CreateModel : PageModel
    {
        private readonly WebShopRM.Models.WebShopRMContext _context;

        public CreateModel(WebShopRM.Models.WebShopRMContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Category Category { get; set; }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Category.Add(Category);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Pages/Categories/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using WebShopRM.Models;

namespace WebShopRM.Pages.Categories
{
    public class DeleteModel : PageModel
    {
        private readonly WebShopRM.Models.WebShopRMContext _context;

        public DeleteModel(WebShopRM.Models.WebShopRMContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Category Category { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Category = await _context.Category.FirstOrDefaultAsync(m => m.CategoryID == id);

            if (Category == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Category = await _context.Category.FindAsync(id);

            if (Category != null)
            {
                _context.Category.Remove(Category);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/Categories/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using WebShopRM.Models;

namespace WebShopRM.Pages.Categories
{
    public class DetailsModel : PageModel
    {
        private readonly WebShopRM.Models.WebShopRMContext _context;

        public DetailsModel(WebShopRM.Models.WebShopRMContext context)
        {
            _context = context;
        }

        public Category Category { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Category = await _context.Category.FirstOrDefaultAsync(m => m.CategoryID == id);

            if (Category == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

Pages/Categories/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebShopRM.Models;

namespace WebShopRM.Pages.Categories
{
    public class EditModel : PageModel
    {
        private readonly WebShopRM.Models.WebShopRMContext _context;

        public EditModel(WebShopRM.Models.WebShopRMContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Category Category { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Category = await _context.Category.FirstOrDefaultAsync(m => m.CategoryID == id);

            if (Category == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Category).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!CategoryExists(Category.CategoryID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool CategoryExists(int id)
        {
            return _context.Category.Any(e => e.CategoryID == id);
        }
    }
}

Pages/Pictures/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebShopRM.Helpers;
using WebShopRM.Models;

namespace WebShopRM.Pages.Pictures
{
    
    public class CreateModel : PageModel
    {
        private readonly WebShopRM.Models.WebShopRMContext _context;
        private IHostingEnvironment _env; //håller reda på sökvägar

        public CreateModel(WebShopRM.Models.WebShopRMContext context, IHostingEnvironment env)
        {
            _context = context;
            _env = env;
        }
        [BindProperty]
        public Picture picture { get; set; }
        
        public IActionResult OnGet()
        {
            //PicturesViewModel picVM = new PicturesViewModel();
            return Page();
        }


        [BindProperty]
        public IFormFile UploadFile { get; set; }
        [BindProperty]
        public string PicName { get; set; }

        public async Task<IActionResult> OnPostAsync()
        {

            if (!ModelState.IsValid)
            {
                return Page();
            }

            var fileExtension = Path.GetExtension(UploadFile.FileName);
            string pictureFolderPath = ImagePathBuilder.NewPath(_env.WebRootPath);
            var picturePath = (Path.Combine(pictureFolderPath, (Guid.NewGuid().ToString())))+ fileExtension;
            
            using (FileStream stream = new FileStream(picturePath, FileMode.Create))
            {

                //await imgFile.CopyToAsync(stream);
                await UploadFile.CopyToAsync(stream);
            }

            int startPosToSelect = picturePath.IndexOf("wwwroot\\Upload", System.StringComparison.CurrentCultureIgnoreCase);
            string relativePicturePath = picturePath.Substring(startPosToSelect + 8); //cut after "wwwroot/"

            Picture picture = new Picture
            {
                PicPath = relativePicturePath,
                PicName = PicName,
                Updated = DateTime.UtcNow
            };


            _context.Picture.Add(picture);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Pages/Pictures/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using WebShopRM.Models;

namespace WebShopRM.Pages.Pictures
{
    public class DeleteModel : PageModel
    {
        private readonly WebShopRM.Models.WebShopRMContext _context;

        public DeleteModel(WebShopRM.Models.WebShopRMContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Picture Picture { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Picture = await _context.Picture.FirstOrDefaultAsync(m => m.PictureID == id);

            if (Picture == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Picture = await _context.Picture.FindAsync(id);

            if (Picture != null)
            {
                _context.Picture.Remove(Picture);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/Products/Catalog.cshtml
@page
@model WebShopRM.Pages.Products.CatalogModel
@addTagHelper *, Microsoft.AapNetCore.MVC.TagHelpers
@{
    ViewData["Title"] = "Catalog";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<form asp-page="./Catalog" method="get">
    <div class="form-actions no-color">
        <p>
            Find by name:
            <input type="text" name="SearchString" value="@Model.CurrentFilter" />
            <input type="submit" value="Search" class="btn btn-primary" /> |
            <a asp-page="./Catalog">Back to full List</a>
        </p>
    </div>
</form>

<table class="table">
    <thead>
        <tr>
            <td>
                <a asp-page="./Catalog" asp-route-sortOrder="@Model.NameSort"
                   asp-route-currentFilter="@Model.CurrentFilter">
                    @Html.DisplayNameFor(model => model.Products[0].ProductName)<text>  &#8645;</text>
                </a>
            </td>
            
            <td>
                <a asp-page="./Catalog" asp-route-sortOrder="@Model.PriceSort"
                   asp-route-currentFilter="@Model.CurrentFilter">
                    @Html.DisplayNameFor(model => model.Products[0].Price)<text>  &#8645;</text>
                </a>
            </td>
            @*<th></th>*@
        </tr>
    </thead>
    <tbody>
        <tr>
            <td colspan="2">
                <div class="container">

                    <div class="card-deck">
                        @foreach (var item in Model.Products)
                        {
                            <div class="card">
                            @*<img class="card-img-top" src="~/@Url.Content(item.picture.PicPath)" style="width:100%" max-height="200px" max-width="100px" />*@


                             <img src="~/@Url.Content(Model.productAndPictures.Where(x=>x.product.Id == item.Id).Select(x=>x.picture.PicPath).FirstOrDefault())" id="imgProduct" /> @*style="width:100%"*@

                                <div class="card-body d-flex flex-column">
                                @*<div class="detailswrapper">*@
                                    <div class="productname">
                                        @Html.DisplayFor(modelItem => item.ProductName)
                                    </div>
                                    <div>
                                        @Html.DisplayFor(modelItem => item.PartNumber)
                                    </div>
                                    <div class="description">
                                        @Html.DisplayFor(modelItem => item.Description)
                                    </div>
                                    <div class="price">
                                        @Html.DisplayFor(modelItem => item.Price)<text> kr</text>
                                    </div>
                                   
                                @*</div>*@
                                <div class="button mr-auto">
                                @*<a id="btn_add" href="@Url.Action("Add", "AddToCart")" class="btn btn-info btn-lg">*@
                                @*<a asp-page="Cart" asp-page-handler="Buy" asp-route-id="@item.Id">Buy</a>*@

                                <a asp-page="/cart/cart" asp-page-handler="buy" asp-route-id="@item.Id">Buy</a>

                                @*@Html.ActionLink("Add to Cart", "AddToBasket", "ShoppingCart", new { id = item.Id }, null)*@
                                    @*<a asp-page="Cart" asp-route-id="@item.Id">Buy</a>*@
                                @*<a asp-action="Cart" asp-route-id="@item.Id">
                                    <span class="glyphicon glyphicon-shopping-cart"></span> Add To Cart
                                </a>*@

                                </div>
                              </div>
                            </div>
                        }
                    </div>
                </div>
            </td>
        </tr>
    </tbody>
</table>

@{
    var prevDisabled = !Model.Products.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.Products.HasNextPage ? "disabled" : "";
}

<a asp-page="./catalog"
   asp-route-sortOrder="@Model.CurrentSort"
   asp-route-pageIndex="@(Model.Products.PageIndex - 1)"
   asp-route-currentFilter="@Model.CurrentFilter"
   class="btn btn-primary @prevDisabled">
    Previous
</a>
<a asp-page="./catalog"
   asp-route-sortOrder="@Model.CurrentSort"
   asp-route-pageIndex="@(Model.Products.PageIndex + 1)"
   asp-route-currentFilter="@Model.CurrentFilter"
   class="btn btn-primary @nextDisabled">
    Next
</a>

<style>
    .card{
        border-style: solid;
       /*border-color: black;*/
        border-radius: 3px;
        border-width: 1px;
        /*background-color:darkturquoise;*/
        /*margin: 2px;*/
        box-shadow: 0px 2px 3px grey, inset 2px 2px 3px white;
        text-shadow: 0px 0px 2px white;
        
    }
    #imgProduct {
        max-height: 200px;
        /*max-width: 300px;*/
        object-fit: contain;

        z-index: 0; /*under card border*/
    }
    .card-body{
        padding:5px;
        flex-direction:row;
        justify-content: space-between;
        align-content: space-between;
    }
    /*.detailswrapper{
        
        justify-content: space-between;
    }*/
    .button{
        
        align-self:flex-end;
        border-style: solid;
        border-width: .5px;
        border-color: black;
        border-radius: 2px;
        box-shadow: 0 0 2px darkgray;

    }
    .price {
        font-weight: bold;
    }
    .productname{
        font-weight: bold;
    }

</style>

Pages/Products/Create.cshtml
@page
@*@model WebShopRM.Models.AddProductVM*@
@model WebShopRM.Pages.Products.CreateModel

@System.Globalization.CultureInfo.CurrentUICulture

@{
    //ViewData["Title"] = "Create";
    //ViewBag[Categories];
    //Html.DropDownList("CategoryID",(MultiSelectList) ViewBag.Categories, new { multiple = "multiple" });
}
    <head>
        <link href="~/css/chosen.min.css" rel="stylesheet" />
    </head>
<h1>Create</h1>

<h4>Product</h4>
<hr />

<div class="row">
    <div class="col-md-4">
        <form method="post">


            @if (Model.AllCategories != null)
            {
                <div class="form-group">
                    <label class="control-label">Välj kategorier / Select categories</label><br />
                    @*@Html.DropDownListFor(model => model.SelectedCategories, new SelectList(Model.AllCategories, "CategoryID", "CategoryName"), new { id="normalDropDown" })*@

                    @Html.ListBoxFor(model => model.SelectedCategories, new MultiSelectList(Model.AllCategories, "CategoryID", "CategoryName"), new { id = "multiSelectDropDown", multiple = "multiple" })<text>Sök eller klicka</text>@*, new { @class = "form-control" } )*@    @*, new { htmlAttributes = new { @class = "form-control" } })*@
                </div>
            }


            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ProductName" class="control-label">Produkt namn / Product name</label>
                <input asp-for="ProductName" class="form-control" />
                <span asp-validation-for="ProductName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PartNumber" class="control-label">Artikelnummer / Part number</label>
                <input asp-for="PartNumber" class="form-control" />
                <span asp-validation-for="PartNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ISBN" class="control-label"></label>
                <input asp-for="ISBN" class="form-control" />
                <span asp-validation-for="ISBN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Beskrivning / Description</label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Price" class="control-label">Utpris / Sales price</label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tax" class="control-label">Moms / Sales tax</label>
                <input asp-for="Tax" class="form-control" />
                @*<span asp-validation-for="Tax" class="text-danger"></span>*@
            </div>
            <div class="form-group">
                <label asp-for="StockQuantity" class="control-label">Antal i lager / Stock quantity</label>
                <input asp-for="StockQuantity" class="form-control" />
                <span asp-validation-for="StockQuantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Visible" class="control-label">Synlig / Visible</label>
                <input asp-for="Visible" class="form-control move-left" type="checkbox" id="chkVisible" />

            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>
@*<script src="js/site.js" asp-append-version="true"></script>*@


@section Scripts {

    @*<script src="js/site.js" asp-append-version="true"></script>
        <script src="~/lib/jquery/dist/chosen.jquery.min.js"></script>
        <script type="text/javascript" src="~/lib/jquery/dist/chosen.jquery.min.js"></script>*@
    <!-- cldr scripts (needed for globalize) -->
    <script src="~/lib/cldrjs/dist/cldr.js"></script>
    <script src="~/lib/cldrjs/dist/cldr/event.js"></script>
    <script src="~/lib/cldrjs/dist/cldr/supplemental.js"></script>

    <script src="~/lib/globalize/globalize.js"></script>
    <script src="~/lib/globalize/globalize/number.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>

    <script src="~/lib/jquery-validation-globalize/jquery.validate.globalize.js"></script>
    <script src="~/lib/globalize/globalize.js"></script>


    <script src="~/js/chosen.jquery.min.js"></script>
    
    @*<script src="~/lib/chosen/chosen.jquery.min.js"></script>
    <script src="~/lib/chosen/chosen.jquery.js"></script>*@

    <script>


        $(function () {
            $("#multiSelectDropDown").chosen()

        });
                                    //multiSelectDropDown
                                    //$(function () {
                                    //    $("#multiSelectDropDown").chosen({
                                    //        width: "60%"
                                    //    });
                                    //});

                                    //dropdown
                                    //$(function () {
                                    //    $("#normalDropDown").chosen({
                                    //        disable_search_threshold: 5
                                    //    });
                                    //});
    </script>

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<style>
    #chkVisible {
        width: 30px;
        height: 30px;
    }

    #multiSelectDropDown {
        width: 100%;
        height: 60px;
        /*border-radius: 10px;
        border-color: lightgray;*/
    }
</style>

Pages/Products/Delete.cshtml
@page
@model WebShopRM.Pages.Products.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.ProductName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.ProductName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.PartNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.PartNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.ISBN)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.ISBN)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.ImagePath)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.ImagePath)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.Updated)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.Updated)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Product.Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>